failure handling in FormsKnotProxy
Knotx/knotx-forms pull request #10
Opened 2018-12-11 12:34 UTC by scypio

Implementation of new knotx feature (fragment processing faiilure handling) within forms

## Description
New failure handling feature was implemented in https://github.com/Cognifide/knotx/issues/466
This PR allows data bridge to take advantage of the new approach and handle data bridge failures in a more robust way.
## Motivation and Context
See core feature documentation

## Screenshots (if appropriate)

## Upgrade notes (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] My code follows the [code style](/CONTRIBUTING.md#coding-conventions) of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

---
I hereby agree to the terms of the Knot.x Contributor License Agreement.

2018-12-11 13:28 UTC, malaskowski requested changes

2018-12-11 13:28 UTC, malaskowski commented on core/src/main/java/io/knotx/forms/core/FormsKnotProxy.java
> +    } catch (Throwable t) {
Please catch only `Exception`.

2018-12-11 13:31 UTC, scypio commented on core/src/main/java/io/knotx/forms/core/FormsKnotProxy.java
> +    } catch (Throwable t) {
fixed

2018-12-12 09:47 UTC, malaskowski approved these changes

2018-12-12 10:22 UTC, merged