Integration and unit tests
Knotx/knotx-forms pull request #6
Opened 2018-10-19 07:50 UTC by bmalecki

Fix integration and unit test. Some code and config refactor.

2018-10-19 13:08 UTC, tomaszmichalak requested changes

2018-10-19 13:08 UTC, tomaszmichalak commented on it-test/src/test/java/io/knotx/forms/test/integration/FormsIntegrationTest.java
> +          Assertions.assertTrue(context.containsKey("action"));
```suggestion
          Assertions.assertTrue(context.containsKey("forms"));
```

2018-10-19 13:08 UTC, tomaszmichalak commented on it-test/src/test/java/io/knotx/forms/test/integration/FormsIntegrationTest.java
> +          Assertions.assertTrue(context.getJsonObject("action").containsKey("_result"));
```suggestion
          Assertions.assertTrue(context.getJsonObject("forms").containsKey("_result"));
```

2018-10-19 13:08 UTC, tomaszmichalak commented on it-test/src/test/java/io/knotx/forms/test/integration/FormsIntegrationTest.java
> +              context.getJsonObject("action").getJsonObject("_result").containsKey("mock"));
```suggestion
              context.getJsonObject("forms").getJsonObject("_result").containsKey("mock"));
```

2018-10-19 13:17 UTC, tomaszmichalak commented on it-test/src/test/java/io/knotx/forms/test/integration/FormsIntegrationTest.java
> +          JsonObject context = knotContext.getFragments().iterator().next().context();
Please add HTTP method to the request. We should validate scenarios:
1. GET request that renders form details without Knot.x specific tags.
2. POST request that calls the mock adapter and passes the flow to the next Knot.
3. POST request that calls the mock adapter and based on signal redirects to the different page.

2018-10-19 13:36 UTC, tomaszmichalak commented on it-test/src/test/java/io/knotx/forms/test/integration/FormsIntegrationTest.java
> +  @KnotxApplyConfiguration("formsStack.conf")
I think we can define the example configuration in `conf` folder:
```
conf/
       formStack.conf
       includes/
                    formsKnot.conf
                    exampleFormAdatper.conf 
```
and then in the test method specify `formsStack.conf` that contains default settings and add `testScenarioXXX.conf` that overrides defaults. The example can be found here: io.knotx.example.monolith.SampleApplicationIntegrationTest#whenRequestingLocalSimplePageWithGetCustomSymbol_expectLocalSimpleHtml.

Additionally we can specify ExampleFormAdapter behaviour based on expected scenarios. So the configuration can be:

exampleFormAdapter.address = ...
exampleFormAdapter.testStrategy = GET_REQUEST

And in the Example Form Adapter we can implement all cases. Please not that both Example Form Adapter and `testScenarioXXX.conf` are defined in tests scope.

2018-10-19 13:44 UTC, tomaszmichalak requested changes

2018-10-19 13:44 UTC, tomaszmichalak commented on conf/formsStack.conf
> +  ####### Forms Adpater #######
Please add links to those configuration files in `README.md`.

2018-10-23 08:32 UTC, bmalecki reviewed
Added test configuration resources

2018-10-23 08:32 UTC, bmalecki commented on conf/formsStack.conf
> +  ####### Forms Adpater #######
Added

2018-10-23 10:56 UTC, tomaszmichalak requested changes

2018-10-23 10:56 UTC, tomaszmichalak commented on core/src/main/java/io/knotx/forms/core/FormsKnotProxy.java
> +    form.fragment().context().put("forms", formsContext);
Extract "forms" to constant in API module.

2018-10-23 10:56 UTC, tomaszmichalak commented on core/src/main/java/io/knotx/forms/core/domain/FormConstants.java
>    static final String FORM_ADAPTER_ATTR = "data-knotx-forms-adapter";
"data-knotx-forms-adapter" -> "data-knotx-forms-adapter-name"

2018-10-23 10:56 UTC, tomaszmichalak commented on core/src/main/java/io/knotx/forms/core/domain/FormConstants.java
> +  static final String FORM_ATTRIBUTES_PATTERN = "data-knotx-.*";
I think we can assume that we search for "data-knotx-forms-.*".

2018-10-23 10:56 UTC, tomaszmichalak commented on it-test/src/test/java/io/knotx/forms/test/integration/FormsIntegrationTest.java
> +  @KnotxApplyConfiguration("formsStack_GET.conf")
`@KnotxApplyConfiguration({"formsStack.conf","adapterGET.conf"})`

?

2018-10-24 09:28 UTC, tomaszmichalak commented on api/src/main/java/io/knotx/forms/api/FormFragmentConstants.java
> +public class FormFragmentConstants {
final

2018-10-24 09:30 UTC, tomaszmichalak commented on api/src/main/java/io/knotx/forms/api/FormFragmentConstants.java
> +public class FormFragmentConstants {
```suggestion
public final class FormFragmentConstants {
```

2018-10-24 09:32 UTC, tomaszmichalak approved these changes

2018-10-24 09:48 UTC, merged